---
title: "02. The RCX and CX Data Model"
Model author: 
- name: Florian J. Auer
  email: Florian.Auer@informatik.uni-augsburg.de
  affiliation: &id University Augsburg
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{RCX Vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTFv2.4.0"}
---

# Meta aspects
## metaData
property			|options							|description
--------------------|-----------------------------------|-------------------------------------------------------
"name"				|Required in pre- and post-metadata	|The name of the aspect
"version"			|Required in pre-metadata			|version of this aspect schema ("1.1.0", "2.0.0", etc.)
"idCounter"			|Required if the aspect exports IDs	|Integer (All Element IDs are integers; see [node id](#nodeid), [edge id](#edgeid), [cytoscape group id](#cygroupid))
"elementCount"      |Optional							|number (integer) of elements in this aspect
"consistencyGroup"	|Optional                           |An integer identifier shared by aspects to indicate that they are mutually consistent
"properties"		|Optional					        |An aspect-defined property list
"checksum"          |Optional (Deprecated) 	            |(NDEx CX implementation doesn???t support this attribute. This attribute is ignored in NDEx)

## status
property   |options   |values          |description
-----------|----------|----------------|------------------------------------------------
"success"  |Required  |TRUE or FALSE   |Was the CX successfully generated by the source
"error"    |Required  |string or ""    |error message or "" if sucess==TRUE

# <a id="datatypes">Data types</a>
data type        |example          |R data type
-----------------|-----------------|---------------
boolean          |"true"           |logical
double           |"2.3"            |numeric
integer          |"23"             |integer       
long             |"123456"         |integer
string           |"blue"           |character
list_of_boolean  |["true","false"] |list(logical)
list_of_double   |["2.3","4.5"]    |list(numeric)
list_of_integer  |["23","45"]      |list(integer)
list_of_long     |["23","45"]      |list(integer)
list_of_string   |["Marco","Polo"] |list(character)

# NDEx CX conventions
## Citations
The citations aspect elements specify literature references or other sources of information that are relevant to the network. Other aspects, such as supports, edgeCitations, or nodeCitations can link them to specific nodes and edges in the network, indicating that the citation supports the assertion represented by the given node or edge.
Citations are primarily described by five [dublin core terms](http://purl.org/dc/terms). The ???dc??? prefix is implicitly interpreted as referencing dublin core in the context of the citations aspect.

The five primary dublin core terms defined for citations are:

* dc:title
    * http://dublincore.org/documents/2012/06/14/dcmi-terms/?v=terms#terms-title
* dc:contributor
    * http://dublincore.org/documents/2012/06/14/dcmi-terms/?v=terms#terms-contributor
* dc:identifier
    + http://dublincore.org/documents/2012/06/14/dcmi-terms/?v=terms#terms-identifier
    + Ideally citations make use of the ???identifier??? key to link to their source. This can be a URI, but might also use the ???source:id??? format, where source is usually ???pmid??? or ???doi???.
* dc:type
    * http://dublincore.org/documents/2012/06/14/dcmi-terms/?v=terms#terms-type
* dc:description
    * http://dublincore.org/documents/2012/06/14/dcmi-terms/?v=elements#description
    * This should be a description of the resource, and it is preferable that information that can be expressed in more specific attributes should not be in this attribute. The ???description??? attribute could contain the title, authors, and/or journal reference, but in that case it would not be expected to be machine parsable.

## Handling of Identifiers
All identifiers should be either:

* $\lt$prefix$\gt$:$\lt$id$\gt$ format
* a string without " : "
* a URI

# Core aspects
* networkAttributes
* nodes				
* nodeAttributes 
* edges 
* edgeAttributes
* cartesianLayout

## networkAttributes
property |options          |values                    |description
---------|-----------------|--------------------------|-----------------------------------------------------------
"n"      |Required         |string                    |attribute name, eg. "dc:title"
"v"      |Required         |string or list of strings |attribute value(s), eg. "Result of heat diffusion analysis"
"d"      |Optional         |string                    |[data type](#datatypes), default "string"
"s"      |Optional         |integer                   |subnetwork id (see [Cytoscape subnetworks](#subnetworkid))

#### NDEx conventions
property            |description
--------------------|---------------------------------------------------------------------------------------------
"version"           |NDEx will treat this attribute as the version of the network. Format is not controlled but best practice is to use string conforming to Semantic Versioning.
"ndex:sourceFormat" |used by NDEx to indicate format of an original file imported, can determine semantics as well. The NDEx UI will allow export options based on this value. Applications that alter a network such that it can no longer be exported in the format should remove the value.
"name"              |the name of the network
"description"       |a description of the network

## nodes				
property |options          |values  |description
---------|-----------------|--------|------------------------------------------------
<a id="nodeid">"@id"</a>|Required, Unique |integer |CX internal node id, starts at 0
"n"      |Optional         |string  |node name, eg. "EGFR", "node 1"
"r"      |Optional         |string  |represents, eg. "HGNC:AKT1"
**Note:** At least one node has to be present!

## nodeAttributes 
property |options          |values                    |description
---------|-----------------|--------------------------|-----------------------------------------------------------
"po"     |Required         |integer                   |property of, reference to CX internal [node id "@id"](#nodeid)
"n"      |Required         |string                    |attribute name, eg. "weight", "name", "selected"
"v"      |Required         |string or list of strings |attribute value(s), eg. ["2", "0.34", "2.3"], "Node 6", "true"
"d"      |Optional         |string                    |[data type](#datatypes), default "string"
"s"      |Optional         |integer                   |subnetwork id (see [Cytoscape subnetworks](#subnetworkid))

#### NDEx conventions
property            |description
--------------------|---------------------------------------------------------------------------------------------
"alias"             |alternative identifiers for the node. Same meaning as BioPAX "aliases"
"relatedTo"         |identifiers denoting concepts related to the node. Same meaning as BioPAX "relatedTerms"

## edges 
property |options          |values  |description
---------|-----------------|--------|------------------------------------------------
<a id="edgeid">"@id"</a>|Required, Unique |integer |CX internal edge id, starts at 0
"s"      |Required         |integer |source, reference to CX internal [node id "@id"](#nodeid)
"t"      |Required         |integer |target, reference to CX internal [node id "@id"](#nodeid)
"i"      |Optional         |string  |intercation, eg. "binds"

## edgeAttributes
property |options          |values                    |description
---------|-----------------|--------------------------|-----------------------------------------------------------
"po"     |Required         |integer                   |property of, reference to CX internal [edge id "@id"](#edgeid)
"n"      |Required         |string                    |attribute name, eg. "weight", "name", "selected"
"v"      |Required         |string or list of strings |attribute value(s), eg. ["2", "0.34", "2.3"], "Node 6", "true"
"d"      |Optional         |string                    |[data type](#datatypes), default "string"
"s"      |Optional         |integer                   |subnetwork id (see [Cytoscape subnetworks](#subnetworkid))

## cartesianLayout
property |options          |values                    |description
---------|-----------------|--------------------------|-----------------------------------------------------------
"node"   |Required         |integer                   |property of, reference to CX internal [node id "@id"](#nodeid)
"x"      |Required         |numeric                   |x coordinate
"y"      |Required         |numeric                   |y coordinate
"z"      |Optional         |numeric                   |z coordinate
"view"   |Optional         |integer                   |view id (see [Cytoscape subnetworks](#cytoscape))

# Cytoscape aspects

## <a id="cytoscape">Properties in other aspects</a>
property |root aspect      |values                    |description
---------|-----------------|--------------------------|-----------------------------------------------------------
"s"      |nodeAttributes <br/> edgeAttributes <br/> networkAttributes|integer |subnetwork id; If not present, refers to the root network (see [Cytoscape subnetworks](#subnetworkid))
"view"   |cartesianLayout  |integer                   |view id; ID used in Cytoscape for views

## cyGroups
property          |options          |values          |description
------------------|-----------------|----------------|------------------------------------------------
<a id="cygroupid">"@id"</a>|Required, Unique |integer         |Cytoscape group id, starts at 0, exported to metaData!
"n"               |Required?        |string          |name of this group
"nodes"           |Required?        |list of integer |the nodes making up the group, reference to CX internal [node id "@id"](#nodeid)
"external_edges"  |Required?        |list of integer |the external edges making up the group, reference to CX internal [edge id "@id"](#edgeid)
"internal_edges"  |Required?        |list of integer |the internal edges making up the group, reference to CX internal [edge id "@id"](#edgeid)
"collapsed"       |Required?        |boolean         |indicate whether the group is displayed as a single node

## cyVisualProperties

See [Cytoscape Styles](http://manual.cytoscape.org/en/stable/Styles.html), [Using Visual Properies in RCy3](https://bioconductor.org/packages/release/bioc/vignettes/RCy3/inst/doc/Custom-Graphics.html) 

property          |options          |values          |description
------------------|-----------------|----------------|------------------------------------------------
"properties_of"   |Required         |string, dictionary|to indicate the element type these properties belong to, allowed values are: "network", "nodes:default", "edges:default", "nodes", "edges"
"applies_to"      |Required         |integer         |the identifier of the element these properties apply to, reference to CX internal [node id "@id"](#nodeid) or [edge id "@id"](#edgeid)
"view"            |Optional         |integer         |[Cytoscape view id](#cytoscape)
"properties"      |Optional         |named list of strings |pairs of the actual properties, e.g. "NODE_BORDER_STROKE" : "SOLID", "NODE_BORDER_WIDTH" : "1.5", "NODE_FILL_COLOR" : "#FF3399"
"dependencies"    |Required         |named list of strings |pairs of the dependencies, e.g. "nodeCustomGraphicsSizeSync" : "true", "nodeSizeLocked" : "false"
"mappings"        |Optional, dictionary |named list of named list of strings | e.g. "NODE_FILL_COLOR" : {"type" : "CONTINUOUS", "definition" : "COL=gal1RGexp,T=double,L=0=#0066CC,E=0=#0066CC,G=0=#0066CC,OV=0=-2.426,L=1=#FFFFFF,E=1=#FFFFFF,G=1=#FFFFFF,OV=1=1.225471493171426E-7,L=2=#FFFF00,E=2=#FFFF00,G=2=#FFFF00,OV=2=2.058"}

## cyHiddenAttributes
property          |options          |values          |description
------------------|-----------------|----------------|------------------------------------------------
"s"               |Optional         |integer                   |subnetwork id (see [Cytoscape subnetworks](#subnetworkid))
"n"               |Required         |string                    |name of this hidden attribute
"v"               |Required         |string or list of strings |attribute value(s), eg. "layoutAlgorithm"
"d"               |Optional         |string                    |[data type](#datatypes), default "string"

## cyNetworkRelations
property          |options          |values          |description
------------------|-----------------|----------------|------------------------------------------------
"p"               |Optional         |integer                   |parent network id (see [Cytoscape subnetworks](#subnetworkid))
"c"               |Required         |integer                   |child network
"r"               |Optional         |string: "view", "subnetwork"|relationship type, default "subnetwork"
"name"            |Optional         |string                    |the name of the child network; if missing, default is reader-dependent

## cySubNetworks 
property |options          |values  |description
---------|-----------------|--------|------------------------------------------------
<a id="subnetworkid">"@id"</a>|Required, Unique |integer |CX/Cytoscape internal id
"nodes"  |Required         |list of integer or "all" |edges making up this subnetwork, reference to CX internal [node id "@id"](#nodeid)
"edges"  |Required         |list of integer or "all" |nodes making up this subnetwork, reference to CX internal [node id "@id"](#edgeid)

## cyTableColum

These elements are used to represent Cytoscape table column labels and types. Its main use is to disambiguate empty table columns.

property          |options          |values          |description
------------------|-----------------|----------------|------------------------------------------------
"s"               |Optional         |integer                   |subnetwork id (see [Cytoscape subnetworks](#subnetworkid))
"n"               |Required         |integer                   |name of the table column
"d"               |Optional         |integer                   |[data type](#datatypes), default "string"
"applies_to"      |Required         |string: "node_table", "edge_table", or "network_table"|indicates the Cytoscape table this applies to 

**Note:** Cytoscape does not currently support table columns for the root network, but this is option is included here for consistency


# Deprecated aspects
property            |description
--------------------|---------------------------------------------------------------------------------------------
"ndexStatus"        |NDEx server will no longer generate this aspect from the server side. Network last updated before the v2.4.0 release will still have this aspect. Users can use the "Get Network Summary" API function to get the status and other information of a network.
"citations"         |We recommend using the attribute "citation" on edges or nodes to store citations.
"nodeCitations"     |We recommend using the attribute "citation" on nodes to store citations.
"edgeCitations"     |We recommend using the attribute "citation" on edges to store citations.
"Supports"          |We recommend using the attribute "supports" on edges or nodes.
"nodeSupports"      |We recommend using the attribute "supports" on nodes.
"edgeSupports"      |We recommend using the attribute "supports" on edges.
"functionTerms"     |No recommendations for alternative representation.
"reiefiedEdges"     |No recommendations for alternative representation.
"@context"          |We recommend using the attribute "@context" on networks. The value of this attribute is a serialized string from a JSON dictionary that has a prefix as its key and a URL as its value. @context maps terms to IRIs. Terms are case sensitive.
"provenanceHistory" |The server will just treat this as an opaque aspect. For recording the origin and significant events of this network, we recommend to use network attributes to store them. We recommend using prov:wasGeneratedBy and prov:wasDerivedFrom for the event and the list of contributing network URLs.

**Note:** Starting from v2.4.0, NDEx server will no longer generate these aspects from the server side. Networks last updated before the v2.4.0 release will still have these aspects.






